### ISSUE TITLE
React Production Build error: "this hasn't been initialized -- super() hasn't been called"

### ISSUE THREAD

**Issue by emfastic** [dolanmiu/docx#1858]
In React's development build everything works fine and the document is created as expected. On production build, "this" is uninitialized causing no document to generate.

I attempted to refactor a functional React component to be class-based as the React examples use and utilize imports in the exact same way. The issue arises on a TextRun call so I believe the error is somewhere in the library's code as this is initialized properly in my class-based refactor of the component.

Below is the error message with stack-trace and the code.

### Error Message

```
Uncaught ReferenceError: this hasn't been initialised - super() hasn't been called
    at e.exports (assertThisInitialized.js:3:11)
    at e.exports (possibleConstructorReturn.js:9:10)
    at new n (index.js:2:224239)
    at new n (index.js:2:225233)
    at n.<anonymous> (createSuper.js:11:24)
    at new n (index.js:2:225355)
    at new n (resume.js:40:11)
    at n.value (CreateResume.jsx:30:29)
    at Object.De (react-dom.production.min.js:54:317)
    at ze (react-dom.production.min.js:54:471)

```

Resume.js
```
import docx, { convertInchesToTwip } from "docx";
import React from "react";

const {
  AlignmentType,
  Document,
  Paragraph,
  TabStopPosition,
  TabStopType,
  TextRun,
} = docx;

const fontType = "Times New Roman";

// divided by 2 gives real font size
const bodyFontSize = 24;

// Redefine because of smaller margins
TabStopPosition.MAX = 12200;

class DocumentCreator extends React.Component {
  constructor() {
    super();
    console.log(
      new Paragraph({
        tabStops: [
          {
            type: TabStopType.RIGHT,
            position: TabStopPosition.MAX,
          },
        ],
        children: [
          new TextRun({
            text: ``,
            bold: true,
            font: {
              name: fontType,
            },
            size: bodyFontSize,
          }),
          new TextRun({  // throws the error here
            text: `\t`, // \t to use the tab stop
            bold: true,
            font: {
              name: fontType,
            },
            size: bodyFontSize,
          }),
        ],
        spacing: { line: 241 }, // add spacing to make sure letters don't get cut off
      })
    );
    }
```

CreateResume.jsx generate
```
class CreateResume extends React.Component {
...

  generate() { // function that triggers error
    ...
    const documentCreator = new DocumentCreator();
    const doc = documentCreator.create([ // function that triggers error
      this.state.experienceObj,
      this.state.educationObj,
      this.state.skillsObj,
      this.props.user,
    ]);

// generate called in button component 
```

**Comment by duylinhdang1998** [comment]
+1 same problem
Please fix that

**Comment by 3chospirits** [comment]
+1

**Comment by duylinhdang1998** [comment]
Downgrade version to 7.7.0
it worked!

**Comment by dolanmiu** [comment]
So sorry about this, I tracked down the root issue, it is because in a constructor, it was returning nothing. For some reason, `eslint` did not complain:

https://github.com/dolanmiu/docx/blob/62d0767cebfb8c1add37ece15abd739c735810b2/src/file/paragraph/run/run-components/text.ts#L26-L30

`return;` is **illegal** in JS, it has to return something.

I am fixing it. Will let you all know when it is released.

**Comment by dolanmiu** [comment]
This is fixed in `7.8.1`. 

Now released. Let me know if there are any further issues.

Appologies for the inconvenience again.

**Comment by ulion** [comment]
Indeed for SymbolRun, it requires the similar fix, I just found that since in my build the SymbolRun constructor pulled the trigger of crash. @dolanmiu

**Comment by ElOscuro29** [comment]
> Lo siento, localicé el problema raíz, es porque en un constructor no devolvía nada. Por alguna razón, `eslint`no se quejó:
> 
> https://github.com/dolanmiu/docx/blob/62d0767cebfb8c1add37ece15abd739c735810b2/src/file/paragraph/run/run-components/text.ts#L26-L30
> 
> `return;`es **ilegal** en JS, tiene que devolver algo.
> 
> lo estoy arreglando Les avisará a todos cuando se publique.

Hello, I still have the same problem, with what version of node did you try it?
I am using 14.8

**Comment by dolanmiu** [comment]
> > Lo siento, localicé el problema raíz, es porque en un constructor no devolvía nada. Por alguna razón, `eslint`no se quejó:
> > https://github.com/dolanmiu/docx/blob/62d0767cebfb8c1add37ece15abd739c735810b2/src/file/paragraph/run/run-components/text.ts#L26-L30
> > 
> > `return;`es **ilegal** en JS, tiene que devolver algo.
> > lo estoy arreglando Les avisará a todos cuando se publique.
> 
> Hello, I still have the same problem, with what version of node did you try it? I am using 14.8

I tried this in React production environment. Not Node. Does it crash on Node 16?

**Comment by dolanmiu** [comment]
> Indeed for SymbolRun, it requires the similar fix, I just found that since in my build the SymbolRun constructor pulled the trigger of the same crash. @dolanmiu

Appologies, this is fixed now in `7.8.2`
